#!/bin/sh
# Interactive language toggle for this Neovim config.
# Run: sh ~/.config/nvim/set-lang.sh
set -eu

config_dir="$(cd "$(dirname "$0")" && pwd)"
local_file="$config_dir/lua/config/langs_local.lua"
defaults_file="$config_dir/lua/config/langs.lua"

if [ ! -f "$defaults_file" ]; then
    echo "langs.lua not found at $defaults_file" >&2
    exit 1
fi

if [ -t 1 ]; then
    RESET=$(printf '\033[0m')
    BOLD=$(printf '\033[1m')
    DIM=$(printf '\033[2m')
    SKY=$(printf '\033[38;2;135;206;235m')
    PINK=$(printf '\033[38;2;255;182;193m')
    SKY2=$(printf '\033[38;2;165;200;225m')
    YELLOW=$(printf '\033[33m')
else
    RESET=''
    BOLD=''
    DIM=''
    SKY=''
    PINK=''
    SKY2=''
    YELLOW=''
fi

# Extract enabled language names from langs.lua.
# (Two greps + sort because BSD grep on macOS mishandles this alternation.)
langs=$({
    grep -E '^[[:space:]]*\["[^"]+"\][[:space:]]*=[[:space:]]*true' "$defaults_file"
    grep -E '^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]*=[[:space:]]*true' "$defaults_file"
} | sed -E 's/^[[:space:]]*//; s/[[:space:]]*=.*$//; s/^\["//; s/"\]$//' | sort -u | tr '\n' ' ')

n=$(echo "$langs" | wc -w | tr -d ' ')
if [ "$n" -eq 0 ]; then
    echo "no languages parsed from $defaults_file" >&2
    exit 1
fi

# Seed disabled state from existing langs_local.lua.
disabled=""
if [ -f "$local_file" ]; then
    disabled=$({
        grep -E '^[[:space:]]*\["[^"]+"\][[:space:]]*=[[:space:]]*false' "$local_file" 2>/dev/null || true
        grep -E '^[[:space:]]*[a-zA-Z_][a-zA-Z0-9_]*[[:space:]]*=[[:space:]]*false' "$local_file" 2>/dev/null || true
    } | sed -E 's/^[[:space:]]*//; s/[[:space:]]*=.*$//; s/^\["//; s/"\]$//' | tr '\n' ' ')
fi

ESC=$(printf '\033')
CR=$(printf '\r')

is_disabled() {
    case " $disabled " in
        *" $1 "*) return 0 ;;
        *) return 1 ;;
    esac
}

toggle() {
    if is_disabled "$1"; then
        disabled=$(echo " $disabled " | sed "s/ $1 / /g; s/^ *//; s/ *$//")
    else
        disabled="$disabled $1"
    fi
}

draw() {
    printf '\033[H\033[J'
    printf '\n'
    printf '   %s%s╭──────────────────────────────────────────────╮%s\n' "$SKY" "$BOLD" "$RESET"
    printf '   %s%s│  %sNeovim language picker%s%s%s                      %s%s│%s\n' \
        "$SKY2" "$BOLD" "$PINK" "$RESET" "$SKY2" "$BOLD" "$SKY2" "$BOLD" "$RESET"
    printf '   %s%s╰──────────────────────────────────────────────╯%s\n' "$PINK" "$BOLD" "$RESET"
    printf '\n'

    i=0
    for lang in $langs; do
        if is_disabled "$lang"; then
            mark="${DIM}[ ]${RESET}"
            name="${DIM}${lang}${RESET}"
        else
            mark="${SKY}[✓]${RESET}"
            name="${lang}"
        fi
        if [ "$i" -eq "$cursor" ]; then
            printf '   %s▸%s  %s  %s\n' "$PINK" "$RESET" "$mark" "$name"
        else
            printf '      %s  %s\n' "$mark" "$name"
        fi
        i=$((i + 1))
    done

    printf '\n'
    printf '   %s%s↑/↓%s move   %s%sspace%s toggle   %s%sa%s all   %s%sn%s none   %s%s↩%s save   %s%sq%s quit\n' \
        "$BOLD" "$PINK" "$RESET" \
        "$BOLD" "$PINK" "$RESET" \
        "$BOLD" "$PINK" "$RESET" \
        "$BOLD" "$PINK" "$RESET" \
        "$BOLD" "$PINK" "$RESET" \
        "$BOLD" "$PINK" "$RESET"
}

cleanup() {
    stty echo icanon 2>/dev/null || true
    printf '\033[?25h'
}
trap cleanup INT TERM EXIT

cursor=0
stty -echo -icanon
printf '\033[?25l'
draw

while :; do
    key=$(dd if=/dev/tty bs=1 count=1 2>/dev/null)
    case "$key" in
        "$ESC")
            rest=$(dd if=/dev/tty bs=1 count=2 2>/dev/null)
            case "$rest" in
                '[A') if [ "$cursor" -gt 0 ]; then cursor=$((cursor - 1)); fi ;;
                '[B') if [ "$cursor" -lt $((n - 1)) ]; then cursor=$((cursor + 1)); fi ;;
            esac
            ;;
        ' ')
            i=0
            for lang in $langs; do
                if [ "$i" -eq "$cursor" ]; then
                    toggle "$lang"
                    break
                fi
                i=$((i + 1))
            done
            ;;
        a | A) disabled='' ;;
        n | N) disabled="$langs" ;;
        "$CR" | '') break ;;
        q | Q)
            cleanup
            printf '\n   %scancelled.%s\n\n' "$YELLOW" "$RESET"
            exit 0
            ;;
    esac
    draw
done

cleanup
printf '\n'

{
    echo '-- Generated by set-lang.sh. Hand-edits are preserved on next run only'
    echo '-- if they match the [name] = false shape parsed by the script.'
    echo 'return {'
    for lang in $disabled; do
        case "$lang" in
            *[!a-zA-Z0-9_]*) printf '    ["%s"] = false,\n' "$lang" ;;
            *) printf '    %s = false,\n' "$lang" ;;
        esac
    done
    echo '}'
} >"$local_file"

printf '   %s✓%s  saved to %s%s%s%s\n' "$PINK" "$RESET" "$SKY" "$BOLD" "$local_file" "$RESET"
printf '   %sℹ%s  restart nvim for changes to take effect.\n\n' "$SKY" "$RESET"
