-- lang → LSP server names. Gated by langs.lua; disabled lang = servers skipped.
-- rust: rustaceanvim owns rust_analyzer. ron: no LSP.
return {
    asm = { "asm_lsp" },
    bash = { "bashls" },
    ["c-cpp"] = { "clangd" },
    cmake = { "neocmake" },
    dockerfile = { "dockerls" },
    elixir = { "elixirls" },
    go = { "gopls" },
    graphql = { "graphql" },
    helm = { "helm_ls" },
    json = { "jsonls" },
    just = { "just" },
    lua = { "lua_ls" },
    markdown = { "marksman", "mdx_analyzer" },
    nix = { "nil_ls" },
    ocaml = { "ocamllsp" },
    protobuf = { "buf_ls" },
    python = { "basedpyright", "ruff" },
    ron = {},
    rust = {},
    shader = { "wgsl_analyzer", "glsl_analyzer" },
    sql = { "sqls" },
    terraform = { "terraformls" },
    toml = { "taplo" },
    typst = { "tinymist" },
    web = { "vtsls", "cssls", "html", "emmet_ls", "tailwindcss" },
    yaml = { "yamlls" },
    zig = { "zls" },
}
