-- Right-edge scrollbar with diagnostic/git marks.
return {
    "petertriho/nvim-scrollbar",
    event = "BufReadPost",
    dependencies = { "lewis6991/gitsigns.nvim" },
    opts = {
        handle = {
            color = "#98ABCC",
            blend = 70,
        },
        marks = {
            Cursor = { color = "#98ABCC" },
            Search = { color = "#E890B0" },
            Error = { color = "#E890B0" },
            Warn = { color = "#E890B0" },
            Info = { color = "#98ABCC" },
            Hint = { color = "#98ABCC" },
            Misc = { color = "#98ABCC" },
            GitAdd = { color = "#98ABCC" },
            GitChange = { color = "#E890B0" },
            GitDelete = { color = "#E890B0" },
        },
        excluded_filetypes = {
            "prompt",
            "snacks_dashboard",
            "neo-tree",
            "neo-tree-popup",
            "Trouble",
            "trouble",
            "dap-repl",
            "dapui_console",
            "dapui_scopes",
            "dapui_breakpoints",
            "dapui_stacks",
            "dapui_watches",
            "aerial",
            "lazy",
            "mason",
            "snacks_picker_input",
            "snacks_picker_list",
            "snacks_terminal",
            "fff_input",
            "fff_list",
            "fff_preview",
            "harpoon",
            "qf",
        },
        handlers = {
            cursor = true,
            diagnostic = true,
            gitsigns = true,
            handle = true,
            search = false,
            ale = false,
        },
    },
}
